version: '3'

services:
  server:
    container_name: server
    build: ./server
    command: >
      /bin/sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver"
    volumes:
      - ./server/:/server
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  client:
    container_name: client
    build: ./client
    volumes:
      - ./client/:/client
    ports:
      - "5173:5173"
    depends_on:
      - db
      - server

  db:
    container_name: db
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flycloud
      - POSTGRES_PASSWORD=flycloud
      - POSTGRES_DB=flycloud_dev

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:8080
    depends_on:
      - server
      - client

volumes:
  postgres_data:
