version: '3'


services:
  backend:
    container_name: backend
    build: ./server
    command: >
      /bin/sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server/:/server
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./client
    volumes:
      - ./client/:/client
    ports:
      - 5173:5173
    depends_on:
      - db
      - backend

  db:
    container_name: db
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flycloud
      - POSTGRES_PASSWORD=flycloud
      - POSTGRES_DB=flycloud_dev
  
  storage:
    container_name: storage
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
        MINIO_ROOT_USER: "minio"
        MINIO_ROOT_PASSWORD: "minio123"
    volumes:
      - ./minio-cache:/data
    command: server --console-address ":9001" /data

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:8080
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
