version: '3'

services:
  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      #client:
      #container_name: client
      #restart: always
      #build:
      #context: .
      #dockerfile: ./compose/client/Dockerfile
      #volumes:
      #  - ./client:/front
      #ports:
      #  - "8080:8080"
      #expose:
      #  - 8080

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
