version: '3'

services:
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: ./compose/server/Dockerfile
    volumes:
      - ./server:/back
    ports:
      - "8000:8000"
    expose:
      - 8000

  client:
    container_name: client
    restart: always
    build:
      context: .
      dockerfile: ./compose/client/Dockerfile
      volumes:
        - ./client:/front
      ports:
        - "8080:8080"
      expose:
        - 8080
